### ISSUE TITLE
USER STORY: Anonymous feedback

### ISSUE THREAD

**Issue by laurakond** [laurakond/My-first-agile-project#4]
In order to **provide anonymous feedback** as a **user**, I can **choose to hide my identity in the poll response**

**Comment by laurakond** [comment]
## Acceptance Criteria
* The option should be provided as a checkbox
* The checkbox should be "checked" by default
* The option should appear next to the submit button
* After submitting the default submission confirmation should be adjusted to include the user name

**Comment by laurakond** [comment]
## Tasks
- [ ] Task 1: Update the view: the poll design (HTML and CSS) to include the checkbox and to show th name of the submitter
- [ ] Task 2: Create a new field in to emodel to track the username
- [ ] Task 3: Update the controller function
- [ ] Task 4: Update unit test scripts
- [ ] Task 5: Test the functionality
